### ISSUE TITLE
package.json for dependent django apps and main entry

### ISSUE THREAD

**Issue by johanneswilm** [kevin1024/django-npm#10]
Hey @kevin1024 & @raphael-boucher,

I have just looked through the readme so far, but this seems like something that could replace our custom solution in Fidus Writer [1] to make npm and django work together. But I have two questions:

1. Would it be possible to extend this to also take into consideration dependent django apps with their own `package.json`? I mean if I create a reusable django app that contains a `package.json` file and from my main app I require this app by entry in `requirements.txt` and a corresponding entry in the settings.py file in`INSTALLED_APPS`, could we make it so that also those are pulled? (As far as I understand the documentation, this is currently not happening.)

2. The documentation seems to say that by default all contents of node_modules are served as static files, or alternatively that only those parts are served that are listed as `NPM_FILE_PATTERNS`. Would it be possible to add an option to only serve those files mentioned as the `main` entry in `package.json`, or would that make no sense?

[1] https://github.com/fiduswriter/fiduswriter

**Comment by ramabouda** [comment]
Hello Johannes,

1. Seems like something we could want, but not so simple to do. We would have to manage the possible version conflicts in JS deps, which would be done by some kind of static assets namespacing by app. Feel free to submit a PR if you have a convenient solution!

2. In your settings file, you could read the `package.json` and put your entry file in `NPM_FILE_PATTERNS`, it seems like the easiest way to do. I don't feel a real need to add it as an option right now, but maybe i'm wrong.

**Comment by johanneswilm** [comment]
As for 1 - right, if two different versions of the same package are required, that won't work.  But that will be a problem anyway. The way I solved in our solution is to look for package.json files in all installed packages and then merge them.

As for 2 - if one has 1, then this is kind of required as an option as the settings.py file won't usually know about all dependencies -
 unless one always wants to serve all node_modules files, right? An alternative could be to specify which files to serve in the package.json of that django app.

For example, we have some plugins that are basically django apps. If one wants to add a plugin, one should only have to do pip install fiduswriter-PLUGINNAME and add an entry to INSTALLED_APPLICATIONS. Does that make sense?

If this doesn't make any sense to you guys, I could also make a fork, but I'd really prefer to share development with you guys.

**Comment by ramabouda** [comment]
Yes, this aproach is interesting.
In your case the merge works fine, but if you don't have control on the JS packages, deps can conflict without an available merge option, if one installed app use a not-retrocompatible version of a lib. I feel this one really requires a kind of namespace for the general case. It might be a namespace by installed app or by major package version...

I agree that if we have 1., 2. will make sense.

**Comment by johanneswilm** [comment]
@raphael-boucher In our case we also import ES6 JS modules from one django app to the other. 

I can see that the name space stuff could be interesting for some use cases, but not exactly ours (and I guess not yours either?) so maybe it would be enough for now simply throw an error or warning to the command line in those cases where two different package.json files that import two different versions of the same package? Then as a second step this more complex name space stuff could be added once someone uses this package with that need.

**Comment by ramabouda** [comment]
Yes, that seems to be a good way to go!
