### ISSUE TITLE
Can you add a license please?

### ISSUE THREAD

**Issue by pkkid** [kevin1024/django-npm#13]
This looks like a useful app we can use, but without a license its a no go for business.

**Comment by jpic** [comment]
Pirate, from latin Pirae, "taking their change", "living for adventure"... :boat:

**Comment by ramabouda** [comment]
@kevin1024 is MIT license ok for you?

**Comment by claytondaley** [comment]
MIT is very permissive so I'd be shocked if anyone said no.  To make it official, can you push a LICENSE file?

**Comment by claytondaley** [comment]
... just found it in setup.py.  Still nice to have a LICENSE.

**Comment by ramabouda** [comment]
Done
