### ISSUE TITLE
Not working while using NPM_FILE_PATTERNS

### ISSUE THREAD

**Issue by habiiev** [kevin1024/django-npm#15]
So when I try to collect files while using NPM_FILE_PATTERNS I get just 0 static files copied. It doesn't work any way, anything that I put there (except for '*') will result in 0 static files copied, and thats with every npm package I try.
![image](https://user-images.githubusercontent.com/31899678/52177361-66042180-27c8-11e9-88f5-c1d5c6785d3d.png)

**Comment by manishkumr** [comment]
I am having similar issue..

**Comment by 0-173** [comment]
For me this turned out to be a windows problem because of the backslash path separator.
The documentation should be modified. This one will help:
```
NPM_FILE_PATTERNS = {
    'what-input': [os.path.join('dist', '*.js')],
}
```
