### ISSUE TITLE
Maintain and improve this package

### ISSUE THREAD

**Issue by ramabouda** [kevin1024/django-npm#4]
Hello,

I'm using this package and would like to maintain it. I already forked it with and made a few improvements. You don't seem to have the time to do it, would you like transfer the ownership, or name me as a co-maintainer ?

Thanks

**Comment by kevin1024** [comment]
Thank you for volunteering!  You're right - I don't seem to have the time to maintain.  However I am using it in production for a few apps and it is working well for my use case.  I see the open PR to stop automatically running npm install.  What other changes do you propose?

**Comment by ramabouda** [comment]
I made a fork here: https://github.com/Polyconseil/django-npm
Changes are:
- Slightly more explicit config names (prefix were confusing)
- Don't `npm install` at the start of the finder
- Optimize finder to not search directories that we can determine out of the given paths
- Optional cache mecanism

Optimizations were required, because the finder slowed very significally the apps, in dev.

**Comment by ramabouda** [comment]
What we can do to avoid breaking compatibility is release a new major version, so you don't need to update your apps, keeping a version 0.X.X. Does this would fit you?

**Comment by kevin1024** [comment]
Yup, sounds good.

**Comment by kevin1024** [comment]
Just gave you commit access.  Welcome to the project!
